apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: envoy
        image: envoy/envoy:latest
        ports:
        - containerPort: 10000
        env:
        - name: FAULT_PERCENTAGE
          value: "50"
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 10000